/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'announcementId' : AnnouncementId,
}
export type AnnouncementId = string;
export type AttendanceId = string;
export interface AttendanceRecord {
  'status' : AttendanceStatus,
  'latitude' : [] | [number],
  'workerId' : WorkerId,
  'date' : string,
  'markedBy' : string,
  'longitude' : [] | [number],
  'timestamp' : Time,
  'recordId' : AttendanceId,
  'photo' : [] | [ExternalBlob],
}
export interface AttendanceRecordPublic {
  'status' : AttendanceStatus,
  'workerId' : WorkerId,
  'date' : string,
  'markedBy' : string,
  'timestamp' : Time,
  'recordId' : AttendanceId,
  'photo' : [] | [ExternalBlob],
}
export type AttendanceStatus = { 'present' : null } |
  { 'leave' : null } |
  { 'absent' : null } |
  { 'holiday' : null };
export type ConfirmationId = string;
export interface DashboardStats {
  'todayAbsent' : bigint,
  'totalWorkers' : bigint,
  'todayPresent' : bigint,
  'twoPMConfirmations' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Holiday {
  'date' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : [] | [string],
  'holidayId' : HolidayId,
}
export type HolidayId = string;
export interface MonthlySummaryEntry {
  'workerId' : WorkerId,
  'presentDays' : bigint,
  'absentDays' : bigint,
  'leaveDays' : bigint,
  'workerName' : string,
}
export interface Note {
  'workerId' : WorkerId,
  'content' : string,
  'noteId' : NoteId,
  'createdAt' : Time,
  'createdBy' : string,
  'noteType' : NoteType,
  'photoUrl' : [] | [ExternalBlob],
  'updatedAt' : [] | [Time],
}
export type NoteId = string;
export type NoteType = { 'work' : null } |
  { 'perWorker' : null } |
  { 'ownerInstruction' : null } |
  { 'material' : null };
export type SalaryId = string;
export interface SalaryRecord {
  'month' : bigint,
  'workerId' : WorkerId,
  'presentDays' : bigint,
  'year' : bigint,
  'netPay' : bigint,
  'manualOverride' : boolean,
  'monthlySalary' : bigint,
  'carryForward' : bigint,
  'advanceAmount' : bigint,
  'absentDays' : bigint,
  'companyHolidays' : bigint,
  'salaryId' : SalaryId,
  'cutDays' : bigint,
}
export type Time = bigint;
export interface TwoPMConfirmation {
  'workerId' : WorkerId,
  'confirmationId' : ConfirmationId,
  'date' : string,
  'confirmedAt' : [] | [Time],
  'confirmed' : boolean,
}
export interface UserProfile {
  'workerId' : [] | [string],
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Worker {
  'pin' : string,
  'workerId' : WorkerId,
  'active' : boolean,
  'name' : string,
  'monthlySalary' : bigint,
  'mobile' : string,
}
export type WorkerId = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<[string, string], AnnouncementId>,
  'addHoliday' : ActorMethod<[string, string, [] | [string]], HolidayId>,
  'addNote' : ActorMethod<
    [WorkerId, NoteType, string, [] | [ExternalBlob]],
    NoteId
  >,
  'addSalaryRecord' : ActorMethod<
    [
      WorkerId,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
    ],
    SalaryId
  >,
  'addWorker' : ActorMethod<[string, string, bigint], WorkerId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeMyPin' : ActorMethod<[string, string], undefined>,
  'changeWorkerPin' : ActorMethod<[WorkerId, string], undefined>,
  'confirmTwoPM' : ActorMethod<[WorkerId], ConfirmationId>,
  'deleteAnnouncement' : ActorMethod<[AnnouncementId], undefined>,
  'deleteHoliday' : ActorMethod<[HolidayId], undefined>,
  'deleteNote' : ActorMethod<[NoteId], undefined>,
  'deleteSalaryRecord' : ActorMethod<[SalaryId], undefined>,
  'deleteWorker' : ActorMethod<[WorkerId], undefined>,
  'editHoliday' : ActorMethod<
    [HolidayId, string, string, [] | [string]],
    undefined
  >,
  'editWorker' : ActorMethod<
    [WorkerId, string, string, bigint, string, boolean],
    undefined
  >,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllHolidays' : ActorMethod<[], Array<Holiday>>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllSalaryRecords' : ActorMethod<[], Array<SalaryRecord>>,
  'getAllWorkers' : ActorMethod<[], Array<Worker>>,
  'getAttendanceByDate' : ActorMethod<
    [WorkerId, string],
    [] | [AttendanceRecordPublic]
  >,
  'getAttendanceByWorker' : ActorMethod<
    [WorkerId],
    Array<AttendanceRecordPublic>
  >,
  'getAttendanceByWorkerForMonth' : ActorMethod<
    [WorkerId, bigint, bigint],
    Array<AttendanceRecordPublic>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConfirmationsByDate' : ActorMethod<[string], Array<TwoPMConfirmation>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMonthlySummary' : ActorMethod<
    [bigint, bigint],
    Array<MonthlySummaryEntry>
  >,
  'getMyConfirmation' : ActorMethod<
    [WorkerId, string],
    [] | [TwoPMConfirmation]
  >,
  'getMyNotes' : ActorMethod<[], Array<Note>>,
  'getNotesByType' : ActorMethod<[NoteType], Array<Note>>,
  'getNotesByWorker' : ActorMethod<[WorkerId], Array<Note>>,
  'getOwnerStatus' : ActorMethod<
    [],
    { 'ownerRegistered' : boolean, 'isOwner' : boolean }
  >,
  'getSalaryRecord' : ActorMethod<
    [WorkerId, bigint, bigint],
    [] | [SalaryRecord]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorker' : ActorMethod<[WorkerId], Worker>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkWorkerPrincipal' : ActorMethod<[WorkerId], undefined>,
  'markAttendance' : ActorMethod<
    [
      WorkerId,
      AttendanceStatus,
      [] | [number],
      [] | [number],
      [] | [ExternalBlob],
    ],
    AttendanceId
  >,
  'ownerAddAttendance' : ActorMethod<
    [WorkerId, string, AttendanceStatus],
    AttendanceId
  >,
  'ownerDeleteAttendance' : ActorMethod<[AttendanceId], undefined>,
  'ownerGetAttendanceByDate' : ActorMethod<
    [WorkerId, string],
    [] | [AttendanceRecord]
  >,
  'ownerGetAttendanceByWorkerForMonth' : ActorMethod<
    [WorkerId, bigint, bigint],
    Array<AttendanceRecord>
  >,
  'ownerGetAttendanceForDate' : ActorMethod<[string], Array<AttendanceRecord>>,
  'ownerUpdateAttendance' : ActorMethod<
    [AttendanceId, AttendanceStatus],
    undefined
  >,
  'registerOwner' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transferOwnership' : ActorMethod<[Principal], undefined>,
  'updateAnnouncement' : ActorMethod<
    [AnnouncementId, string, string],
    undefined
  >,
  'updateHoliday' : ActorMethod<
    [HolidayId, string, string, [] | [string]],
    undefined
  >,
  'updateNote' : ActorMethod<[NoteId, string, [] | [ExternalBlob]], undefined>,
  'updateSalaryRecord' : ActorMethod<
    [
      SalaryId,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      boolean,
      [] | [bigint],
    ],
    undefined
  >,
  'updateWorker' : ActorMethod<
    [WorkerId, string, string, bigint, string, boolean],
    undefined
  >,
  'validateWorkerLogin' : ActorMethod<
    [WorkerId, string],
    [] | [{ 'workerId' : WorkerId, 'name' : string, 'role' : string }]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];