/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AnnouncementId = IDL.Text;
export const HolidayId = IDL.Text;
export const WorkerId = IDL.Text;
export const NoteType = IDL.Variant({
  'work' : IDL.Null,
  'perWorker' : IDL.Null,
  'ownerInstruction' : IDL.Null,
  'material' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const NoteId = IDL.Text;
export const SalaryId = IDL.Text;
export const ConfirmationId = IDL.Text;
export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'announcementId' : AnnouncementId,
});
export const Holiday = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Opt(IDL.Text),
  'holidayId' : HolidayId,
});
export const Note = IDL.Record({
  'workerId' : WorkerId,
  'content' : IDL.Text,
  'noteId' : NoteId,
  'createdAt' : Time,
  'createdBy' : IDL.Text,
  'noteType' : NoteType,
  'photoUrl' : IDL.Opt(ExternalBlob),
  'updatedAt' : IDL.Opt(Time),
});
export const SalaryRecord = IDL.Record({
  'month' : IDL.Nat,
  'workerId' : WorkerId,
  'presentDays' : IDL.Nat,
  'year' : IDL.Nat,
  'netPay' : IDL.Int,
  'manualOverride' : IDL.Bool,
  'monthlySalary' : IDL.Nat,
  'carryForward' : IDL.Int,
  'advanceAmount' : IDL.Nat,
  'absentDays' : IDL.Nat,
  'companyHolidays' : IDL.Nat,
  'salaryId' : SalaryId,
  'cutDays' : IDL.Nat,
});
export const Worker = IDL.Record({
  'pin' : IDL.Text,
  'workerId' : WorkerId,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'monthlySalary' : IDL.Nat,
  'mobile' : IDL.Text,
});
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'leave' : IDL.Null,
  'absent' : IDL.Null,
  'holiday' : IDL.Null,
});
export const AttendanceId = IDL.Text;
export const AttendanceRecordPublic = IDL.Record({
  'status' : AttendanceStatus,
  'workerId' : WorkerId,
  'date' : IDL.Text,
  'markedBy' : IDL.Text,
  'timestamp' : Time,
  'recordId' : AttendanceId,
  'photo' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'workerId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const TwoPMConfirmation = IDL.Record({
  'workerId' : WorkerId,
  'confirmationId' : ConfirmationId,
  'date' : IDL.Text,
  'confirmedAt' : IDL.Opt(Time),
  'confirmed' : IDL.Bool,
});
export const DashboardStats = IDL.Record({
  'todayAbsent' : IDL.Nat,
  'totalWorkers' : IDL.Nat,
  'todayPresent' : IDL.Nat,
  'twoPMConfirmations' : IDL.Nat,
});
export const MonthlySummaryEntry = IDL.Record({
  'workerId' : WorkerId,
  'presentDays' : IDL.Nat,
  'absentDays' : IDL.Nat,
  'leaveDays' : IDL.Nat,
  'workerName' : IDL.Text,
});
export const AttendanceRecord = IDL.Record({
  'status' : AttendanceStatus,
  'latitude' : IDL.Opt(IDL.Float64),
  'workerId' : WorkerId,
  'date' : IDL.Text,
  'markedBy' : IDL.Text,
  'longitude' : IDL.Opt(IDL.Float64),
  'timestamp' : Time,
  'recordId' : AttendanceId,
  'photo' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [AnnouncementId], []),
  'addHoliday' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [HolidayId],
      [],
    ),
  'addNote' : IDL.Func(
      [WorkerId, NoteType, IDL.Text, IDL.Opt(ExternalBlob)],
      [NoteId],
      [],
    ),
  'addSalaryRecord' : IDL.Func(
      [
        WorkerId,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Int,
        IDL.Nat,
      ],
      [SalaryId],
      [],
    ),
  'addWorker' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [WorkerId], []),
  'changeMyPin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'changeWorkerPin' : IDL.Func([WorkerId, IDL.Text], [], []),
  'confirmTwoPM' : IDL.Func([WorkerId], [ConfirmationId], []),
  'deleteAnnouncement' : IDL.Func([AnnouncementId], [], []),
  'deleteHoliday' : IDL.Func([HolidayId], [], []),
  'deleteNote' : IDL.Func([NoteId], [], []),
  'deleteSalaryRecord' : IDL.Func([SalaryId], [], []),
  'deleteWorker' : IDL.Func([WorkerId], [], []),
  'editHoliday' : IDL.Func(
      [HolidayId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'editWorker' : IDL.Func(
      [WorkerId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllSalaryRecords' : IDL.Func([], [IDL.Vec(SalaryRecord)], ['query']),
  'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'getAttendanceByDate' : IDL.Func(
      [WorkerId, IDL.Text],
      [IDL.Opt(AttendanceRecordPublic)],
      ['query'],
    ),
  'getAttendanceByWorker' : IDL.Func(
      [WorkerId],
      [IDL.Vec(AttendanceRecordPublic)],
      ['query'],
    ),
  'getAttendanceByWorkerForMonth' : IDL.Func(
      [WorkerId, IDL.Nat, IDL.Nat],
      [IDL.Vec(AttendanceRecordPublic)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getConfirmationsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TwoPMConfirmation)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMonthlySummary' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(MonthlySummaryEntry)],
      ['query'],
    ),
  'getMyConfirmation' : IDL.Func(
      [WorkerId, IDL.Text],
      [IDL.Opt(TwoPMConfirmation)],
      ['query'],
    ),
  'getMyNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getNotesByType' : IDL.Func([NoteType], [IDL.Vec(Note)], ['query']),
  'getNotesByWorker' : IDL.Func([WorkerId], [IDL.Vec(Note)], ['query']),
  'getOwnerStatus' : IDL.Func(
      [],
      [IDL.Record({ 'ownerRegistered' : IDL.Bool, 'isOwner' : IDL.Bool })],
      ['query'],
    ),
  'getSalaryRecord' : IDL.Func(
      [WorkerId, IDL.Nat, IDL.Nat],
      [IDL.Opt(SalaryRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorker' : IDL.Func([WorkerId], [Worker], ['query']),
  'linkWorkerPrincipal' : IDL.Func([WorkerId], [], []),
  'markAttendance' : IDL.Func(
      [
        WorkerId,
        AttendanceStatus,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(ExternalBlob),
      ],
      [AttendanceId],
      [],
    ),
  'ownerAddAttendance' : IDL.Func(
      [WorkerId, IDL.Text, AttendanceStatus],
      [AttendanceId],
      [],
    ),
  'ownerDeleteAttendance' : IDL.Func([AttendanceId], [], []),
  'ownerGetAttendanceByDate' : IDL.Func(
      [WorkerId, IDL.Text],
      [IDL.Opt(AttendanceRecord)],
      ['query'],
    ),
  'ownerGetAttendanceByWorkerForMonth' : IDL.Func(
      [WorkerId, IDL.Nat, IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'ownerGetAttendanceForDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'ownerUpdateAttendance' : IDL.Func([AttendanceId, AttendanceStatus], [], []),
  'registerOwner' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transferOwnership' : IDL.Func([IDL.Principal], [], []),
  'updateAnnouncement' : IDL.Func([AnnouncementId, IDL.Text, IDL.Text], [], []),
  'updateHoliday' : IDL.Func(
      [HolidayId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'updateSalaryRecord' : IDL.Func(
      [
        SalaryId,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Int,
        IDL.Nat,
        IDL.Bool,
        IDL.Opt(IDL.Int),
      ],
      [],
      [],
    ),
  'updateWorker' : IDL.Func(
      [WorkerId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'validateWorkerLogin' : IDL.Func(
      [WorkerId, IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'workerId' : WorkerId,
            'name' : IDL.Text,
            'role' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AnnouncementId = IDL.Text;
  const HolidayId = IDL.Text;
  const WorkerId = IDL.Text;
  const NoteType = IDL.Variant({
    'work' : IDL.Null,
    'perWorker' : IDL.Null,
    'ownerInstruction' : IDL.Null,
    'material' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const NoteId = IDL.Text;
  const SalaryId = IDL.Text;
  const ConfirmationId = IDL.Text;
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'announcementId' : AnnouncementId,
  });
  const Holiday = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Opt(IDL.Text),
    'holidayId' : HolidayId,
  });
  const Note = IDL.Record({
    'workerId' : WorkerId,
    'content' : IDL.Text,
    'noteId' : NoteId,
    'createdAt' : Time,
    'createdBy' : IDL.Text,
    'noteType' : NoteType,
    'photoUrl' : IDL.Opt(ExternalBlob),
    'updatedAt' : IDL.Opt(Time),
  });
  const SalaryRecord = IDL.Record({
    'month' : IDL.Nat,
    'workerId' : WorkerId,
    'presentDays' : IDL.Nat,
    'year' : IDL.Nat,
    'netPay' : IDL.Int,
    'manualOverride' : IDL.Bool,
    'monthlySalary' : IDL.Nat,
    'carryForward' : IDL.Int,
    'advanceAmount' : IDL.Nat,
    'absentDays' : IDL.Nat,
    'companyHolidays' : IDL.Nat,
    'salaryId' : SalaryId,
    'cutDays' : IDL.Nat,
  });
  const Worker = IDL.Record({
    'pin' : IDL.Text,
    'workerId' : WorkerId,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'monthlySalary' : IDL.Nat,
    'mobile' : IDL.Text,
  });
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'leave' : IDL.Null,
    'absent' : IDL.Null,
    'holiday' : IDL.Null,
  });
  const AttendanceId = IDL.Text;
  const AttendanceRecordPublic = IDL.Record({
    'status' : AttendanceStatus,
    'workerId' : WorkerId,
    'date' : IDL.Text,
    'markedBy' : IDL.Text,
    'timestamp' : Time,
    'recordId' : AttendanceId,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'workerId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const TwoPMConfirmation = IDL.Record({
    'workerId' : WorkerId,
    'confirmationId' : ConfirmationId,
    'date' : IDL.Text,
    'confirmedAt' : IDL.Opt(Time),
    'confirmed' : IDL.Bool,
  });
  const DashboardStats = IDL.Record({
    'todayAbsent' : IDL.Nat,
    'totalWorkers' : IDL.Nat,
    'todayPresent' : IDL.Nat,
    'twoPMConfirmations' : IDL.Nat,
  });
  const MonthlySummaryEntry = IDL.Record({
    'workerId' : WorkerId,
    'presentDays' : IDL.Nat,
    'absentDays' : IDL.Nat,
    'leaveDays' : IDL.Nat,
    'workerName' : IDL.Text,
  });
  const AttendanceRecord = IDL.Record({
    'status' : AttendanceStatus,
    'latitude' : IDL.Opt(IDL.Float64),
    'workerId' : WorkerId,
    'date' : IDL.Text,
    'markedBy' : IDL.Text,
    'longitude' : IDL.Opt(IDL.Float64),
    'timestamp' : Time,
    'recordId' : AttendanceId,
    'photo' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [AnnouncementId], []),
    'addHoliday' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [HolidayId],
        [],
      ),
    'addNote' : IDL.Func(
        [WorkerId, NoteType, IDL.Text, IDL.Opt(ExternalBlob)],
        [NoteId],
        [],
      ),
    'addSalaryRecord' : IDL.Func(
        [
          WorkerId,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Int,
          IDL.Nat,
        ],
        [SalaryId],
        [],
      ),
    'addWorker' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [WorkerId], []),
    'changeMyPin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'changeWorkerPin' : IDL.Func([WorkerId, IDL.Text], [], []),
    'confirmTwoPM' : IDL.Func([WorkerId], [ConfirmationId], []),
    'deleteAnnouncement' : IDL.Func([AnnouncementId], [], []),
    'deleteHoliday' : IDL.Func([HolidayId], [], []),
    'deleteNote' : IDL.Func([NoteId], [], []),
    'deleteSalaryRecord' : IDL.Func([SalaryId], [], []),
    'deleteWorker' : IDL.Func([WorkerId], [], []),
    'editHoliday' : IDL.Func(
        [HolidayId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'editWorker' : IDL.Func(
        [WorkerId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllSalaryRecords' : IDL.Func([], [IDL.Vec(SalaryRecord)], ['query']),
    'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'getAttendanceByDate' : IDL.Func(
        [WorkerId, IDL.Text],
        [IDL.Opt(AttendanceRecordPublic)],
        ['query'],
      ),
    'getAttendanceByWorker' : IDL.Func(
        [WorkerId],
        [IDL.Vec(AttendanceRecordPublic)],
        ['query'],
      ),
    'getAttendanceByWorkerForMonth' : IDL.Func(
        [WorkerId, IDL.Nat, IDL.Nat],
        [IDL.Vec(AttendanceRecordPublic)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getConfirmationsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TwoPMConfirmation)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMonthlySummary' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(MonthlySummaryEntry)],
        ['query'],
      ),
    'getMyConfirmation' : IDL.Func(
        [WorkerId, IDL.Text],
        [IDL.Opt(TwoPMConfirmation)],
        ['query'],
      ),
    'getMyNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getNotesByType' : IDL.Func([NoteType], [IDL.Vec(Note)], ['query']),
    'getNotesByWorker' : IDL.Func([WorkerId], [IDL.Vec(Note)], ['query']),
    'getOwnerStatus' : IDL.Func(
        [],
        [IDL.Record({ 'ownerRegistered' : IDL.Bool, 'isOwner' : IDL.Bool })],
        ['query'],
      ),
    'getSalaryRecord' : IDL.Func(
        [WorkerId, IDL.Nat, IDL.Nat],
        [IDL.Opt(SalaryRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorker' : IDL.Func([WorkerId], [Worker], ['query']),
    'linkWorkerPrincipal' : IDL.Func([WorkerId], [], []),
    'markAttendance' : IDL.Func(
        [
          WorkerId,
          AttendanceStatus,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(ExternalBlob),
        ],
        [AttendanceId],
        [],
      ),
    'ownerAddAttendance' : IDL.Func(
        [WorkerId, IDL.Text, AttendanceStatus],
        [AttendanceId],
        [],
      ),
    'ownerDeleteAttendance' : IDL.Func([AttendanceId], [], []),
    'ownerGetAttendanceByDate' : IDL.Func(
        [WorkerId, IDL.Text],
        [IDL.Opt(AttendanceRecord)],
        ['query'],
      ),
    'ownerGetAttendanceByWorkerForMonth' : IDL.Func(
        [WorkerId, IDL.Nat, IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'ownerGetAttendanceForDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'ownerUpdateAttendance' : IDL.Func(
        [AttendanceId, AttendanceStatus],
        [],
        [],
      ),
    'registerOwner' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transferOwnership' : IDL.Func([IDL.Principal], [], []),
    'updateAnnouncement' : IDL.Func(
        [AnnouncementId, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateHoliday' : IDL.Func(
        [HolidayId, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'updateSalaryRecord' : IDL.Func(
        [
          SalaryId,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Int,
          IDL.Nat,
          IDL.Bool,
          IDL.Opt(IDL.Int),
        ],
        [],
        [],
      ),
    'updateWorker' : IDL.Func(
        [WorkerId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'validateWorkerLogin' : IDL.Func(
        [WorkerId, IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'workerId' : WorkerId,
              'name' : IDL.Text,
              'role' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };