/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface SalaryRecord {
    month: bigint;
    workerId: WorkerId;
    presentDays: bigint;
    year: bigint;
    netPay: bigint;
    manualOverride: boolean;
    monthlySalary: bigint;
    carryForward: bigint;
    advanceAmount: bigint;
    absentDays: bigint;
    companyHolidays: bigint;
    salaryId: SalaryId;
    cutDays: bigint;
}
export type Time = bigint;
export type NoteId = string;
export type HolidayId = string;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type SalaryId = string;
export interface TwoPMConfirmation {
    workerId: WorkerId;
    confirmationId: ConfirmationId;
    date: string;
    confirmedAt?: Time;
    confirmed: boolean;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type ConfirmationId = string;
export type AttendanceId = string;
export interface Announcement {
    title: string;
    content: string;
    createdAt: Time;
    announcementId: AnnouncementId;
}
export type AnnouncementId = string;
export type WorkerId = string;
export interface AttendanceRecord {
    status: AttendanceStatus;
    latitude?: number;
    workerId: WorkerId;
    date: string;
    markedBy: string;
    longitude?: number;
    timestamp: Time;
    recordId: AttendanceId;
    photo?: ExternalBlob;
}
export interface Holiday {
    date: string;
    name: string;
    createdAt: Time;
    description?: string;
    holidayId: HolidayId;
}
export interface Worker {
    pin: string;
    workerId: WorkerId;
    active: boolean;
    name: string;
    monthlySalary: bigint;
    mobile: string;
}
export interface UserProfile {
    workerId?: string;
    name: string;
    role: string;
}
export interface Note {
    workerId: WorkerId;
    content: string;
    noteId: NoteId;
    createdAt: Time;
    createdBy: string;
    noteType: NoteType;
    photoUrl?: ExternalBlob;
    updatedAt?: Time;
}
export enum AttendanceStatus {
    present = "present",
    leave = "leave",
    absent = "absent",
    holiday = "holiday"
}
export enum NoteType {
    work = "work",
    perWorker = "perWorker",
    ownerInstruction = "ownerInstruction",
    material = "material"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAnnouncement(title: string, content: string): Promise<AnnouncementId>;
    addHoliday(date: string, name: string, description: string | null): Promise<HolidayId>;
    addNote(workerId: WorkerId, noteType: NoteType, content: string, photoUrl: ExternalBlob | null): Promise<NoteId>;
    addSalaryRecord(workerId: WorkerId, month: bigint, year: bigint, monthlySalary: bigint, presentDays: bigint, absentDays: bigint, cutDays: bigint, advanceAmount: bigint, carryForward: bigint, companyHolidays: bigint): Promise<SalaryId>;
    addWorker(name: string, mobile: string, monthlySalary: bigint): Promise<WorkerId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    confirmTwoPM(workerId: WorkerId): Promise<ConfirmationId>;
    deleteAnnouncement(announcementId: AnnouncementId): Promise<void>;
    deleteHoliday(holidayId: HolidayId): Promise<void>;
    deleteNote(noteId: NoteId): Promise<void>;
    deleteSalaryRecord(salaryId: SalaryId): Promise<void>;
    deleteWorker(workerId: WorkerId): Promise<void>;
    editHoliday(holidayId: HolidayId, date: string, name: string, description: string | null): Promise<void>;
    editWorker(workerId: WorkerId, name: string, mobile: string, monthlySalary: bigint, pin: string, active: boolean): Promise<void>;
    getAllAnnouncements(): Promise<Array<Announcement>>;
    getAllHolidays(): Promise<Array<Holiday>>;
    getAllNotes(): Promise<Array<Note>>;
    getAllSalaryRecords(): Promise<Array<SalaryRecord>>;
    getAllWorkers(): Promise<Array<Worker>>;
    getAttendanceByDate(workerId: WorkerId, date: string): Promise<AttendanceRecord | null>;
    getAttendanceByWorker(workerId: WorkerId): Promise<Array<AttendanceRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConfirmationsByDate(date: string): Promise<Array<TwoPMConfirmation>>;
    getMyConfirmation(workerId: WorkerId, date: string): Promise<TwoPMConfirmation | null>;
    getMyNotes(): Promise<Array<Note>>;
    getNotesByType(noteType: NoteType): Promise<Array<Note>>;
    getOwnerStatus(): Promise<{
        ownerRegistered: boolean;
        isOwner: boolean;
    }>;
    getSalaryRecord(workerId: WorkerId, month: bigint, year: bigint): Promise<SalaryRecord | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorker(workerId: WorkerId): Promise<Worker>;
    isCallerAdmin(): Promise<boolean>;
    markAttendance(workerId: WorkerId, status: AttendanceStatus, latitude: number | null, longitude: number | null, photo: ExternalBlob | null): Promise<AttendanceId>;
    ownerAddAttendance(workerId: WorkerId, date: string, status: AttendanceStatus): Promise<AttendanceId>;
    ownerDeleteAttendance(recordId: AttendanceId): Promise<void>;
    ownerUpdateAttendance(recordId: AttendanceId, status: AttendanceStatus): Promise<void>;
    registerOwner(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAnnouncement(announcementId: AnnouncementId, title: string, content: string): Promise<void>;
    updateHoliday(holidayId: HolidayId, date: string, name: string, description: string | null): Promise<void>;
    updateNote(noteId: NoteId, content: string, photoUrl: ExternalBlob | null): Promise<void>;
    updateSalaryRecord(salaryId: SalaryId, monthlySalary: bigint, presentDays: bigint, absentDays: bigint, cutDays: bigint, advanceAmount: bigint, carryForward: bigint, companyHolidays: bigint, manualOverride: boolean, overrideNetPay: bigint | null): Promise<void>;
    updateWorker(workerId: WorkerId, name: string, mobile: string, monthlySalary: bigint, pin: string, active: boolean): Promise<void>;
}
import type { AttendanceId as _AttendanceId, AttendanceRecord as _AttendanceRecord, AttendanceStatus as _AttendanceStatus, ConfirmationId as _ConfirmationId, ExternalBlob as _ExternalBlob, Holiday as _Holiday, HolidayId as _HolidayId, Note as _Note, NoteId as _NoteId, NoteType as _NoteType, SalaryRecord as _SalaryRecord, Time as _Time, TwoPMConfirmation as _TwoPMConfirmation, UserProfile as _UserProfile, UserRole as _UserRole, WorkerId as _WorkerId, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAnnouncement(arg0: string, arg1: string): Promise<AnnouncementId> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnnouncement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnnouncement(arg0, arg1);
            return result;
        }
    }
    async addHoliday(arg0: string, arg1: string, arg2: string | null): Promise<HolidayId> {
        if (this.processError) {
            try {
                const result = await this.actor.addHoliday(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHoliday(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addNote(arg0: WorkerId, arg1: NoteType, arg2: string, arg3: ExternalBlob | null): Promise<NoteId> {
        if (this.processError) {
            try {
                const result = await this.actor.addNote(arg0, to_candid_NoteType_n9(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNote(arg0, to_candid_NoteType_n9(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addSalaryRecord(arg0: WorkerId, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: bigint): Promise<SalaryId> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalaryRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalaryRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async addWorker(arg0: string, arg1: string, arg2: bigint): Promise<WorkerId> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorker(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorker(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmTwoPM(arg0: WorkerId): Promise<ConfirmationId> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmTwoPM(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmTwoPM(arg0);
            return result;
        }
    }
    async deleteAnnouncement(arg0: AnnouncementId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return result;
        }
    }
    async deleteHoliday(arg0: HolidayId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHoliday(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHoliday(arg0);
            return result;
        }
    }
    async deleteNote(arg0: NoteId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async deleteSalaryRecord(arg0: SalaryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSalaryRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSalaryRecord(arg0);
            return result;
        }
    }
    async deleteWorker(arg0: WorkerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorker(arg0);
            return result;
        }
    }
    async editHoliday(arg0: HolidayId, arg1: string, arg2: string, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editHoliday(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editHoliday(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async editWorker(arg0: WorkerId, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editWorker(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editWorker(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async getAllAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncements();
            return result;
        }
    }
    async getAllHolidays(): Promise<Array<Holiday>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHolidays();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHolidays();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotes();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotes();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSalaryRecords(): Promise<Array<SalaryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSalaryRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSalaryRecords();
            return result;
        }
    }
    async getAllWorkers(): Promise<Array<Worker>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkers();
            return result;
        }
    }
    async getAttendanceByDate(arg0: WorkerId, arg1: string): Promise<AttendanceRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByDate(arg0, arg1);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByDate(arg0, arg1);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceByWorker(arg0: WorkerId): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceByWorker(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceByWorker(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConfirmationsByDate(arg0: string): Promise<Array<TwoPMConfirmation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfirmationsByDate(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfirmationsByDate(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyConfirmation(arg0: WorkerId, arg1: string): Promise<TwoPMConfirmation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyConfirmation(arg0, arg1);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyConfirmation(arg0, arg1);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotes();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotes();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesByType(arg0: NoteType): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByType(to_candid_NoteType_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByType(to_candid_NoteType_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnerStatus(): Promise<{
        ownerRegistered: boolean;
        isOwner: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerStatus();
            return result;
        }
    }
    async getSalaryRecord(arg0: WorkerId, arg1: bigint, arg2: bigint): Promise<SalaryRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalaryRecord(arg0, arg1, arg2);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalaryRecord(arg0, arg1, arg2);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorker(arg0: WorkerId): Promise<Worker> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorker(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAttendance(arg0: WorkerId, arg1: AttendanceStatus, arg2: number | null, arg3: number | null, arg4: ExternalBlob | null): Promise<AttendanceId> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, to_candid_AttendanceStatus_n44(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, to_candid_AttendanceStatus_n44(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async ownerAddAttendance(arg0: WorkerId, arg1: string, arg2: AttendanceStatus): Promise<AttendanceId> {
        if (this.processError) {
            try {
                const result = await this.actor.ownerAddAttendance(arg0, arg1, to_candid_AttendanceStatus_n44(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ownerAddAttendance(arg0, arg1, to_candid_AttendanceStatus_n44(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async ownerDeleteAttendance(arg0: AttendanceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.ownerDeleteAttendance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ownerDeleteAttendance(arg0);
            return result;
        }
    }
    async ownerUpdateAttendance(arg0: AttendanceId, arg1: AttendanceStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.ownerUpdateAttendance(arg0, to_candid_AttendanceStatus_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ownerUpdateAttendance(arg0, to_candid_AttendanceStatus_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async registerOwner(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerOwner();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerOwner();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAnnouncement(arg0: AnnouncementId, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnouncement(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnouncement(arg0, arg1, arg2);
            return result;
        }
    }
    async updateHoliday(arg0: HolidayId, arg1: string, arg2: string, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHoliday(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHoliday(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateNote(arg0: NoteId, arg1: string, arg2: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1, await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1, await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateSalaryRecord(arg0: SalaryId, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: boolean, arg9: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSalaryRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSalaryRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async updateWorker(arg0: WorkerId, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorker(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorker(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
async function from_candid_AttendanceRecord_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): Promise<AttendanceRecord> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Holiday_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Holiday): Holiday {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_NoteType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoteType): NoteType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_Note_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Promise<Note> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TwoPMConfirmation_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TwoPMConfirmation): TwoPMConfirmation {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AttendanceRecord]): Promise<AttendanceRecord | null> {
    return value.length === 0 ? null : await from_candid_AttendanceRecord_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TwoPMConfirmation]): TwoPMConfirmation | null {
    return value.length === 0 ? null : from_candid_TwoPMConfirmation_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SalaryRecord]): SalaryRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    name: string;
    createdAt: _Time;
    description: [] | [string];
    holidayId: _HolidayId;
}): {
    date: string;
    name: string;
    createdAt: Time;
    description?: string;
    holidayId: HolidayId;
} {
    return {
        date: value.date,
        name: value.name,
        createdAt: value.createdAt,
        description: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.description)),
        holidayId: value.holidayId
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    workerId: _WorkerId;
    content: string;
    noteId: _NoteId;
    createdAt: _Time;
    createdBy: string;
    noteType: _NoteType;
    photoUrl: [] | [_ExternalBlob];
    updatedAt: [] | [_Time];
}): Promise<{
    workerId: WorkerId;
    content: string;
    noteId: NoteId;
    createdAt: Time;
    createdBy: string;
    noteType: NoteType;
    photoUrl?: ExternalBlob;
    updatedAt?: Time;
}> {
    return {
        workerId: value.workerId,
        content: value.content,
        noteId: value.noteId,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        noteType: from_candid_NoteType_n22(_uploadFile, _downloadFile, value.noteType),
        photoUrl: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.photoUrl)),
        updatedAt: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.updatedAt))
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AttendanceStatus;
    latitude: [] | [number];
    workerId: _WorkerId;
    date: string;
    markedBy: string;
    longitude: [] | [number];
    timestamp: _Time;
    recordId: _AttendanceId;
    photo: [] | [_ExternalBlob];
}): Promise<{
    status: AttendanceStatus;
    latitude?: number;
    workerId: WorkerId;
    date: string;
    markedBy: string;
    longitude?: number;
    timestamp: Time;
    recordId: AttendanceId;
    photo?: ExternalBlob;
}> {
    return {
        status: from_candid_AttendanceStatus_n30(_uploadFile, _downloadFile, value.status),
        latitude: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.latitude)),
        workerId: value.workerId,
        date: value.date,
        markedBy: value.markedBy,
        longitude: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.longitude)),
        timestamp: value.timestamp,
        recordId: value.recordId,
        photo: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.photo))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    workerId: [] | [string];
    name: string;
    role: string;
}): {
    workerId?: string;
    name: string;
    role: string;
} {
    return {
        workerId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.workerId)),
        name: value.name,
        role: value.role
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    workerId: _WorkerId;
    confirmationId: _ConfirmationId;
    date: string;
    confirmedAt: [] | [_Time];
    confirmed: boolean;
}): {
    workerId: WorkerId;
    confirmationId: ConfirmationId;
    date: string;
    confirmedAt?: Time;
    confirmed: boolean;
} {
    return {
        workerId: value.workerId,
        confirmationId: value.confirmationId,
        date: value.date,
        confirmedAt: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.confirmedAt)),
        confirmed: value.confirmed
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    work: null;
} | {
    perWorker: null;
} | {
    ownerInstruction: null;
} | {
    material: null;
}): NoteType {
    return "work" in value ? NoteType.work : "perWorker" in value ? NoteType.perWorker : "ownerInstruction" in value ? NoteType.ownerInstruction : "material" in value ? NoteType.material : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    leave: null;
} | {
    absent: null;
} | {
    holiday: null;
}): AttendanceStatus {
    return "present" in value ? AttendanceStatus.present : "leave" in value ? AttendanceStatus.leave : "absent" in value ? AttendanceStatus.absent : "holiday" in value ? AttendanceStatus.holiday : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Holiday>): Array<Holiday> {
    return value.map((x)=>from_candid_Holiday_n16(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Promise<Array<Note>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Note_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Promise<Array<AttendanceRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AttendanceRecord_n28(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TwoPMConfirmation>): Array<TwoPMConfirmation> {
    return value.map((x)=>from_candid_TwoPMConfirmation_n40(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_NoteType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteType): _NoteType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    workerId?: string;
    name: string;
    role: string;
}): {
    workerId: [] | [string];
    name: string;
    role: string;
} {
    return {
        workerId: value.workerId ? candid_some(value.workerId) : candid_none(),
        name: value.name,
        role: value.role
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteType): {
    work: null;
} | {
    perWorker: null;
} | {
    ownerInstruction: null;
} | {
    material: null;
} {
    return value == NoteType.work ? {
        work: null
    } : value == NoteType.perWorker ? {
        perWorker: null
    } : value == NoteType.ownerInstruction ? {
        ownerInstruction: null
    } : value == NoteType.material ? {
        material: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    present: null;
} | {
    leave: null;
} | {
    absent: null;
} | {
    holiday: null;
} {
    return value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.leave ? {
        leave: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value == AttendanceStatus.holiday ? {
        holiday: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
