/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AnnouncementId = IDL.Text;
export const WorkerId = IDL.Text;
export const NoteType = IDL.Variant({
  'work' : IDL.Null,
  'perWorker' : IDL.Null,
  'ownerInstruction' : IDL.Null,
  'material' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const NoteId = IDL.Text;
export const SalaryId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ConfirmationId = IDL.Text;
export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'announcementId' : AnnouncementId,
});
export const Note = IDL.Record({
  'workerId' : WorkerId,
  'content' : IDL.Text,
  'noteId' : NoteId,
  'createdAt' : Time,
  'createdBy' : IDL.Text,
  'noteType' : NoteType,
  'photoUrl' : IDL.Opt(ExternalBlob),
  'updatedAt' : IDL.Opt(Time),
});
export const SalaryRecord = IDL.Record({
  'month' : IDL.Nat,
  'workerId' : WorkerId,
  'presentDays' : IDL.Nat,
  'year' : IDL.Nat,
  'netPay' : IDL.Int,
  'manualOverride' : IDL.Bool,
  'monthlySalary' : IDL.Nat,
  'carryForward' : IDL.Int,
  'advanceAmount' : IDL.Nat,
  'absentDays' : IDL.Nat,
  'companyHolidays' : IDL.Nat,
  'salaryId' : SalaryId,
  'cutDays' : IDL.Nat,
});
export const Worker = IDL.Record({
  'pin' : IDL.Text,
  'workerId' : WorkerId,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'monthlySalary' : IDL.Nat,
  'mobile' : IDL.Text,
});
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'leave' : IDL.Null,
  'absent' : IDL.Null,
  'holiday' : IDL.Null,
});
export const AttendanceId = IDL.Text;
export const AttendanceRecord = IDL.Record({
  'status' : AttendanceStatus,
  'workerId' : WorkerId,
  'date' : IDL.Text,
  'markedBy' : IDL.Text,
  'timestamp' : Time,
  'recordId' : AttendanceId,
});
export const UserProfile = IDL.Record({
  'workerId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const TwoPMConfirmation = IDL.Record({
  'workerId' : WorkerId,
  'confirmationId' : ConfirmationId,
  'date' : IDL.Text,
  'confirmedAt' : IDL.Opt(Time),
  'confirmed' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [AnnouncementId], []),
  'addNote' : IDL.Func(
      [WorkerId, NoteType, IDL.Text, IDL.Opt(ExternalBlob)],
      [NoteId],
      [],
    ),
  'addSalaryRecord' : IDL.Func(
      [
        WorkerId,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Int,
        IDL.Nat,
      ],
      [SalaryId],
      [],
    ),
  'addWorker' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [WorkerId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmTwoPM' : IDL.Func([WorkerId], [ConfirmationId], []),
  'deleteAnnouncement' : IDL.Func([AnnouncementId], [], []),
  'deleteNote' : IDL.Func([NoteId], [], []),
  'deleteSalaryRecord' : IDL.Func([SalaryId], [], []),
  'deleteWorker' : IDL.Func([WorkerId], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllSalaryRecords' : IDL.Func([], [IDL.Vec(SalaryRecord)], ['query']),
  'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'getAttendanceByDate' : IDL.Func(
      [WorkerId, IDL.Text],
      [IDL.Opt(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByWorker' : IDL.Func(
      [WorkerId],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConfirmationsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TwoPMConfirmation)],
      ['query'],
    ),
  'getMyConfirmation' : IDL.Func(
      [WorkerId, IDL.Text],
      [IDL.Opt(TwoPMConfirmation)],
      ['query'],
    ),
  'getMyNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getNotesByType' : IDL.Func([NoteType], [IDL.Vec(Note)], ['query']),
  'getSalaryRecord' : IDL.Func(
      [WorkerId, IDL.Nat, IDL.Nat],
      [IDL.Opt(SalaryRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorker' : IDL.Func([WorkerId], [Worker], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([WorkerId, AttendanceStatus], [AttendanceId], []),
  'ownerAddAttendance' : IDL.Func(
      [WorkerId, IDL.Text, AttendanceStatus],
      [AttendanceId],
      [],
    ),
  'ownerDeleteAttendance' : IDL.Func([AttendanceId], [], []),
  'ownerUpdateAttendance' : IDL.Func([AttendanceId, AttendanceStatus], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAnnouncement' : IDL.Func([AnnouncementId, IDL.Text, IDL.Text], [], []),
  'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'updateSalaryRecord' : IDL.Func(
      [
        SalaryId,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Int,
        IDL.Nat,
        IDL.Bool,
        IDL.Opt(IDL.Int),
      ],
      [],
      [],
    ),
  'updateWorker' : IDL.Func(
      [WorkerId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AnnouncementId = IDL.Text;
  const WorkerId = IDL.Text;
  const NoteType = IDL.Variant({
    'work' : IDL.Null,
    'perWorker' : IDL.Null,
    'ownerInstruction' : IDL.Null,
    'material' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const NoteId = IDL.Text;
  const SalaryId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ConfirmationId = IDL.Text;
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'announcementId' : AnnouncementId,
  });
  const Note = IDL.Record({
    'workerId' : WorkerId,
    'content' : IDL.Text,
    'noteId' : NoteId,
    'createdAt' : Time,
    'createdBy' : IDL.Text,
    'noteType' : NoteType,
    'photoUrl' : IDL.Opt(ExternalBlob),
    'updatedAt' : IDL.Opt(Time),
  });
  const SalaryRecord = IDL.Record({
    'month' : IDL.Nat,
    'workerId' : WorkerId,
    'presentDays' : IDL.Nat,
    'year' : IDL.Nat,
    'netPay' : IDL.Int,
    'manualOverride' : IDL.Bool,
    'monthlySalary' : IDL.Nat,
    'carryForward' : IDL.Int,
    'advanceAmount' : IDL.Nat,
    'absentDays' : IDL.Nat,
    'companyHolidays' : IDL.Nat,
    'salaryId' : SalaryId,
    'cutDays' : IDL.Nat,
  });
  const Worker = IDL.Record({
    'pin' : IDL.Text,
    'workerId' : WorkerId,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'monthlySalary' : IDL.Nat,
    'mobile' : IDL.Text,
  });
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'leave' : IDL.Null,
    'absent' : IDL.Null,
    'holiday' : IDL.Null,
  });
  const AttendanceId = IDL.Text;
  const AttendanceRecord = IDL.Record({
    'status' : AttendanceStatus,
    'workerId' : WorkerId,
    'date' : IDL.Text,
    'markedBy' : IDL.Text,
    'timestamp' : Time,
    'recordId' : AttendanceId,
  });
  const UserProfile = IDL.Record({
    'workerId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const TwoPMConfirmation = IDL.Record({
    'workerId' : WorkerId,
    'confirmationId' : ConfirmationId,
    'date' : IDL.Text,
    'confirmedAt' : IDL.Opt(Time),
    'confirmed' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [AnnouncementId], []),
    'addNote' : IDL.Func(
        [WorkerId, NoteType, IDL.Text, IDL.Opt(ExternalBlob)],
        [NoteId],
        [],
      ),
    'addSalaryRecord' : IDL.Func(
        [
          WorkerId,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Int,
          IDL.Nat,
        ],
        [SalaryId],
        [],
      ),
    'addWorker' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [WorkerId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmTwoPM' : IDL.Func([WorkerId], [ConfirmationId], []),
    'deleteAnnouncement' : IDL.Func([AnnouncementId], [], []),
    'deleteNote' : IDL.Func([NoteId], [], []),
    'deleteSalaryRecord' : IDL.Func([SalaryId], [], []),
    'deleteWorker' : IDL.Func([WorkerId], [], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllSalaryRecords' : IDL.Func([], [IDL.Vec(SalaryRecord)], ['query']),
    'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'getAttendanceByDate' : IDL.Func(
        [WorkerId, IDL.Text],
        [IDL.Opt(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByWorker' : IDL.Func(
        [WorkerId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConfirmationsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TwoPMConfirmation)],
        ['query'],
      ),
    'getMyConfirmation' : IDL.Func(
        [WorkerId, IDL.Text],
        [IDL.Opt(TwoPMConfirmation)],
        ['query'],
      ),
    'getMyNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getNotesByType' : IDL.Func([NoteType], [IDL.Vec(Note)], ['query']),
    'getSalaryRecord' : IDL.Func(
        [WorkerId, IDL.Nat, IDL.Nat],
        [IDL.Opt(SalaryRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorker' : IDL.Func([WorkerId], [Worker], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func(
        [WorkerId, AttendanceStatus],
        [AttendanceId],
        [],
      ),
    'ownerAddAttendance' : IDL.Func(
        [WorkerId, IDL.Text, AttendanceStatus],
        [AttendanceId],
        [],
      ),
    'ownerDeleteAttendance' : IDL.Func([AttendanceId], [], []),
    'ownerUpdateAttendance' : IDL.Func(
        [AttendanceId, AttendanceStatus],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAnnouncement' : IDL.Func(
        [AnnouncementId, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'updateSalaryRecord' : IDL.Func(
        [
          SalaryId,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Int,
          IDL.Nat,
          IDL.Bool,
          IDL.Opt(IDL.Int),
        ],
        [],
        [],
      ),
    'updateWorker' : IDL.Func(
        [WorkerId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };